### ISSUE TITLE
Crash 7-14-18

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#13]
```
[01:37:10] [Server thread/WARN]: Failed to handle packet for /128.153.192.93:49444
java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:52) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:81) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:107) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:447) ~[ahb.class:?]
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:94) ~[MultipartGenerator$.class:?]
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:599) ~[TileMultipart$.class:?]
	at codechicken.microblock.AdditionPlacement.place(MicroblockPlacement.scala:24) ~[AdditionPlacement.class:?]
	at codechicken.microblock.ItemMicroPart.func_77648_a(ItemMicroPart.scala:73) ~[ItemMicroPart.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:86) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[01:37:10] [Server thread/INFO]: jrddunbr lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[01:37:10] [Server thread/INFO]: jrddunbr left the game
```

**Comment by jrddunbr** [comment]
In review, this is related to copying micro-blocks with WorldEdit. It's probably a non-issue for this repository.
