### ISSUE TITLE
Crash on Creative

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#206]
Unknown provenance, clientside only. Server is still chugging along.

```
[15:34:45] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientCustomPacketEvent@6b302cc5:
java.lang.NullPointerException
[15:34:45] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[15:34:45] [Client thread/ERROR] [FML]: 0: NORMAL
[15:34:45] [Client thread/ERROR] [FML]: 1: ASM: mods.eln.client.ClientPacketHandler@3f1ef988 onClientPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientCustomPacketEvent;)V
[15:34:45] [Client thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.NullPointerException
[15:34:45] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel miaouMod
java.lang.NullPointerException
```

This continues to boot off all LLv14.4 clients.

**Comment by Grissess** [comment]
Found a more proximate log:

```
[15:31:41] [Client thread/INFO] [STDOUT]: [mods.eln.sound.LoopedSoundManager:process:38]: java.lang.IllegalArgumentException: value already present: mods.eln.mechanical.ShaftRender$ShaftSoundLooper@5722dd64
[15:31:41] [Client thread/INFO] [STDOUT]: [mods.eln.sound.LoopedSoundManager:process:38]: java.lang.IllegalArgumentException: value already present: mods.eln.mechanical.ShaftRender$ShaftSoundLooper@1b9eb6be
[15:31:41] [Client thread/INFO] [STDOUT]: [mods.eln.sound.LoopedSoundManager:process:38]: java.lang.IllegalArgumentException: value already present: mods.eln.mechanical.ShaftRender$ShaftSoundLooper@7b4ff296
[15:33:50] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientCustomPacketEvent@4d327102:
java.lang.NullPointerException
	at mods.eln.node.six.SixNodeEntity.serverPublishUnserialize(SixNodeEntity.java:71) ~[SixNodeEntity.class:?]
	at mods.eln.PacketHandler.packetNodeSingleSerialized(PacketHandler.java:205) ~[PacketHandler.class:?]
	at mods.eln.PacketHandler.packetRx(PacketHandler.java:52) ~[PacketHandler.class:?]
	at mods.eln.client.ClientPacketHandler.onClientPacket(ClientPacketHandler.java:31) ~[ClientPacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_507_ClientPacketHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:33:50] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[15:33:50] [Client thread/ERROR] [FML]: 0: NORMAL
[15:33:50] [Client thread/ERROR] [FML]: 1: ASM: mods.eln.client.ClientPacketHandler@3f1ef988 onClientPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientCustomPacketEvent;)V
[15:33:50] [Client thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.NullPointerException
	at mods.eln.node.six.SixNodeEntity.serverPublishUnserialize(SixNodeEntity.java:71) ~[SixNodeEntity.class:?]
	at mods.eln.PacketHandler.packetNodeSingleSerialized(PacketHandler.java:205) ~[PacketHandler.class:?]
	at mods.eln.PacketHandler.packetRx(PacketHandler.java:52) ~[PacketHandler.class:?]
	at mods.eln.client.ClientPacketHandler.onClientPacket(ClientPacketHandler.java:31) ~[ClientPacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_507_ClientPacketHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:33:50] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel miaouMod
java.lang.NullPointerException
	at mods.eln.node.six.SixNodeEntity.serverPublishUnserialize(SixNodeEntity.java:71) ~[SixNodeEntity.class:?]
	at mods.eln.PacketHandler.packetNodeSingleSerialized(PacketHandler.java:205) ~[PacketHandler.class:?]
	at mods.eln.PacketHandler.packetRx(PacketHandler.java:52) ~[PacketHandler.class:?]
	at mods.eln.client.ClientPacketHandler.onClientPacket(ClientPacketHandler.java:31) ~[ClientPacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_507_ClientPacketHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_u212-Exherbo]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_u212-Exherbo]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_u212-Exherbo]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Grissess** [comment]
It appears to come down to some [suspicious lines](https://github.com/jrddunbr/ElectricalAge/blob/60fd3fc850dad8b4d76ab10bd75602c4ff6c3ef4/src/main/java/mods/eln/node/six/SixNodeEntity.java#L70-L71) in ELN's SixNode core. IDEA is warning me about unchecked casts, but I'm not entirely sure which part is nulling out, or why this code has gone so far without an error like this.

I'll make it more robust in a moment and start iterating on it, but I have _no_ way of testing, unfortunately, so I'll be coding this hotfix blind (unless someone has a consistently crashing map, e.g.).

**Comment by jrddunbr** [comment]
Not so fast GitHub. There's still an issue here that we're working at. This is just a ... temporary fix.
