### ISSUE TITLE
Resistor Infinity bug with Lamp Socket

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#255]
```
[15:07:37] [Server thread/INFO] [ELN]: Error! Resistor cannot be set to Infinity
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.Throwable
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mods.eln.sim.electrical.mna.component.Resistor.setR(Resistor.java:54)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mods.eln.sixnode.lampsocket.LampSocketElement.computeElectricalLoad(LampSocketElement.java:289)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mods.eln.sixnode.lampsocket.LampSocketProcess.process(LampSocketProcess.kt:120)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mods.eln.sim.Simulator.tick(Simulator.java:473)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_7_Simulator_tick_ServerTickEvent.invoke(.dynamic)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:603)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
[15:07:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

```

**Comment by jrddunbr** [comment]
Fixed in c703f7b46dd627a490899f7256ec8f91d5efda3d
