### ISSUE TITLE
Transparent Node getting cast into a SixNode

### ISSUE THREAD

**Issue by Caeleron** [jrddunbr/ElectricalAge#260]
A crash occurs here: https://github.com/CoFH/CoFHCore/blob/4be193afe63bcf108c5ad5abd34da34028434c65/src/main/java/cofh/asmhooks/HooksCore.java#L106

with this stacktrace:
```
java.lang.ClassCastException: mods.eln.node.transparent.TransparentNode cannot be cast to mods.eln.node.six.SixNode
	at mods.eln.node.six.SixNodeBlock.nodeHasCache(SixNodeBlock.kt:379)
	at mods.eln.node.six.SixNodeBlock.func_149668_a(SixNodeBlock.kt:55)
	at net.minecraft.block.Block.func_149743_a(Block.java:567)
	at cofh.asmhooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:106)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:110)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

I am not sure if this is a consequence of CoFH Core, Kotlin is more stringent about this type conversion when Java saw it as fine, or if this was a mistake in translation into Kotlin.

**Comment by jrddunbr** [comment]
I would need to see the world file to be able to debug this. It is likely to actually be world corruption.
